source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and all GitHub-supported plugins
gem "github-pages", group: :jekyll_plugins

# Additional plugins
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"

# Required for Ruby 3.0+
gem "webrick"

# Required for Ruby 3.4+
gem "csv"
gem "base64"
gem "bigdecimal"

# Development dependencies (optional)
group :development do
  gem "html-proofer"
end
